### ISSUE TITLE
'@/component/loadable'里只暴露出withRouter，/route/index.jsx里,为何能import Bundle from '@/component/loadable';

### ISSUE THREAD

**Issue by shen-lan** [WinmezzZ/react-antd-admin#1]
如题。

**Comment by WinmezzZ** [comment]
说清楚点，没听明白，况且loadble里没有withRouter吧

**Comment by shen-lan** [comment]
![2](https://user-images.githubusercontent.com/21122615/44703943-2aa05100-aacc-11e8-9349-a627e810204f.png)
![1](https://user-images.githubusercontent.com/21122615/44703944-2b38e780-aacc-11e8-820f-38a976fd3eda.png)

**Comment by shen-lan** [comment]
图二 暴露出一个函数，但是并没有暴露出Bundle ，
为何能引入Bundle呢

**Comment by WinmezzZ** [comment]
loadable模块是全量的导出  ，用了export default后，withLoadable就仅仅只是个name 的作用，没有更多实际意义。import bundle from xx，bundle只是个接收的变量名。
