### ISSUE TITLE
Issue with Proxy and deploying

### ISSUE THREAD

**Issue by Sesleone** [WinmezzZ/react-antd-admin#12]
Can someone help with  in how to deploy to your server   plus how to configure different mocks . Am willing to improve the documentation for this once someone helps me understand

**Comment by WinmezzZ** [comment]
What's your server using? 

Like I'm using Nginx, this is my configure file
```
server {
    listen                      80;
    server_name           www.yourdomain.com or localhost;
    root                        /build folder path;
    index                      index.html index.htm;
    gzip                        on;

    location / {
        try_files  $uri $uri/ /index.html;
    }
}
```

Then just start your nginx server, every thing will be ok.

As for the mock data you can copy this file [https://github.com/WinmezzZ/react-antd-admin/blob/master/src/mock/user/menu.mock.ts](https://github.com/WinmezzZ/react-antd-admin/blob/master/src/mock/user/menu.mock.ts), change the data model(interface) to the structure what you need,  at last don't forget import the mock file you created to `src/mock/index.ts` file.

If any other problem, you can keep asking questions here.

**Comment by WinmezzZ** [comment]
> Can someone help with in how to deploy to your server plus how to configure different mocks . Am willing to improve the documentation for this once someone helps me understand

What's your server using? 

Like I'm using Nginx, this is my configure file
```
server {
    listen                      80;
    server_name           www.yourdomain.com or localhost;
    root                        /build folder path;
    index                      index.html index.htm;
    gzip                        on;

    location / {
        try_files  $uri $uri/ /index.html;
    }
}
```

Then just start your nginx server, every thing will be ok.

As for the mock data you can copy this file [https://github.com/WinmezzZ/react-antd-admin/blob/master/src/mock/user/menu.mock.ts](https://github.com/WinmezzZ/react-antd-admin/blob/master/src/mock/user/menu.mock.ts), change the data model(interface) to the structure what you need,  at last don't forget import the mock file you created to `src/mock/index.ts` file.

If any other problem, you can keep asking questions here.

**Comment by Sesleone** [comment]
Also am using firebase to serve the application and the backend is in a vps with nginx

**Comment by WinmezzZ** [comment]
> Also am using firebase to serve the application and the backend is in a vps with nginx

ummm... Maybe it was caused by publicPath? I can't locate your problem position accurately from you description
