### ISSUE TITLE
启动报错Property 'pop' does not exist on type 'ReactText[] 

### ISSUE THREAD

**Issue by xungegeblue** [WinmezzZ/react-antd-admin#13]
环境:Mac
报错信息:
TypeScript error in /Users/xxx/Public/tmp/react-antd-admin/src/pages/layout/menu.tsx(64,47):
Property 'pop' does not exist on type 'ReactText[] | { key: ReactText; item: ReactInstance; trigger: string; open: boolean; }'.
  Property 'pop' does not exist on type '{ key: ReactText; item: ReactInstance; trigger: string; open: boolean; }'.  TS2339

    62 |       selectedKeys={selectedKeys}
    63 |       openKeys={openKeys}
  > 64 |       onOpenChange={keys => setOpenkeys([keys.pop()!])}
       |                                               ^
    65 |       className="layout-page-sider-menu"
    66 |     >
    67 |       {menuList?.map(menu =>

**Comment by WinmezzZ** [comment]
可能是自动版本的问题，已添加 yarn.lock 文件，删除 node_modules 目录重新执行 yarn 命令

**Comment by WinmezzZ** [comment]
> > 可能是自动版本的问题，已添加 yarn.lock 文件，删除 node_modules 目录重新执行 yarn 命令
> 
> 这不是ts提示的报错么，你的回答文不对题，建议你可以自己先复现一下问题再回答用户比较好吧

感觉你不太聪明的样子，我都说了可能是因为我没有上传版本锁定文件，导致他下载了最新版的antd，与现有代码不兼容。你要是不是百分百确定我说的话是什么意思建议你先思考下再评论别人的回家比较好吧
其次，已经确认复现了他的问题的原因就是如此
