### ISSUE TITLE
BrowserRouter刷新转到index.html在哪里配置的啊

### ISSUE THREAD

**Issue by modelwright** [WinmezzZ/react-antd-admin#14]

**Comment by WinmezzZ** [comment]
`Nginx`:
```nginx
location / {
  try_files $uri $uri/ /index.html;
}
```

`Apache`
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```

`Node`
```javascript
var history = require('connect-history-api-fallback');
var express = require('express');

var app = express();
app.use(history());
```

`IIS`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="Handle History Mode and custom 404/500" stopProcessing="true">
          <match url="(.*)" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
```

`Caddy`
```
rewrite {
    regexp .*
    to {path} /
}
```

**Comment by lghcode** [comment]
> `Nginx`：
> 
> ```nginx
> 位置 / {
>    try_files  $ uri  $ uri / /index.html;
> }
> ```
> 
> `Apache`
> 
> ```
> <IfModule mod_rewrite.c>
>   RewriteEngine On
>   RewriteBase /
>   RewriteRule ^index\.html$ - [L]
>   RewriteCond %{REQUEST_FILENAME} !-f
>   RewriteCond %{REQUEST_FILENAME} !-d
>   RewriteRule . /index.html [L]
> </IfModule>
> ```
> 
> `Node`
> 
> ```js
> var  history  =  require （'connect-history-api-fallback' ）; 
> var  express  =  require （'express' ）;
> 
> var  app  =  express （）; 
> 应用程式。使用（历史（））;
> ```
> 
> `IIS`
> 
> ```
> <？xml 版本 = “ 1.0 ”编码 = “ UTF-8 ”？>
> < 配置 >
>   < 系统 .webServer>
>     < 重写 >
>       < 规则 >
>         < 规则 名称 = “处理历史记录模式和自定义404/500 ”  stopProcessing = “ true ” >
>           < match  url = “（。*）” />
>           < 条件 logicalGrouping = “ MatchAll ” >
>             < 添加 输入 = “ {REQUEST_FILENAME} ”  matchType = “ IsFile ”  negate = “ true ” />
>             < 添加 输入 = “ {REQUEST_FILENAME} ”  matchType = “ IsDirectory ”  negate = “ true ” />
>           </ 条件 >
>           < 操作 类型 = “重写”  url = “ / ” />
>         </ rule >
>       </ 规则 >
>     </ 重写 >
>   </ system .webServer>
> </ 配置 >
> ```
> 
> `Caddy`
> 
> ```
> rewrite {
>     regexp .*
>     to {path} /
> }
> ```

咋没有tomcat的 :）

**Comment by WinmezzZ** [comment]
> > `Nginx`：
> 
> > 
> 
> > ```nginx
> 
> > 位置 / {
> 
> >    try_files  $ uri  $ uri / /index.html;
> 
> > }
> 
> > ```
> 
> > 
> 
> > `Apache`
> 
> > 
> 
> > ```
> 
> > <IfModule mod_rewrite.c>
> 
> >   RewriteEngine On
> 
> >   RewriteBase /
> 
> >   RewriteRule ^index\.html$ - [L]
> 
> >   RewriteCond %{REQUEST_FILENAME} !-f
> 
> >   RewriteCond %{REQUEST_FILENAME} !-d
> 
> >   RewriteRule . /index.html [L]
> 
> > </IfModule>
> 
> > ```
> 
> > 
> 
> > `Node`
> 
> > 
> 
> > ```js
> 
> > var  history  =  require （'connect-history-api-fallback' ）; 
> 
> > var  express  =  require （'express' ）;
> 
> > 
> 
> > var  app  =  express （）; 
> 
> > 应用程式。使用（历史（））;
> 
> > ```
> 
> > 
> 
> > `IIS`
> 
> > 
> 
> > ```
> 
> > <？xml 版本 = “ 1.0 ”编码 = “ UTF-8 ”？>
> 
> > < 配置 >
> 
> >   < 系统 .webServer>
> 
> >     < 重写 >
> 
> >       < 规则 >
> 
> >         < 规则 名称 = “处理历史记录模式和自定义404/500 ”  stopProcessing = “ true ” >
> 
> >           < match  url = “（。*）” />
> 
> >           < 条件 logicalGrouping = “ MatchAll ” >
> 
> >             < 添加 输入 = “ {REQUEST_FILENAME} ”  matchType = “ IsFile ”  negate = “ true ” />
> 
> >             < 添加 输入 = “ {REQUEST_FILENAME} ”  matchType = “ IsDirectory ”  negate = “ true ” />
> 
> >           </ 条件 >
> 
> >           < 操作 类型 = “重写”  url = “ / ” />
> 
> >         </ rule >
> 
> >       </ 规则 >
> 
> >     </ 重写 >
> 
> >   </ system .webServer>
> 
> > </ 配置 >
> 
> > ```
> 
> > 
> 
> > `Caddy`
> 
> > 
> 
> > ```
> 
> > rewrite {
> 
> >     regexp .*
> 
> >     to {path} /
> 
> > }
> 
> > ```
> 
> 
> 
> 咋没有tomcat的 :）

`Tomcat`
编辑 WEB-INF/web.xml

添加以下：

```xml
<web-app>
<error-page>  
<error-code>404</error-code>  
<location>/index.html</location>  
</error-page>  
</web-app>
```
