### ISSUE TITLE
打包白屏

### ISSUE THREAD

**Issue by yuyunzhi** [WinmezzZ/react-antd-admin#19]
兄弟，原项目yarn build 打包白屏。。。。咋解决？？？报错信息，，，because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by WinmezzZ** [comment]
什么系统什么版本，什么浏览器什么版本，什么本地 node 版本，什么服务器，再发下服务器配置
ps: 建议了解一下《提问的艺术》

**Comment by yuyunzhi** [comment]
解决了。。。。。打包路径的问题。
在config-overrides.js里加一下这个吧

  rewiredSourceMap(),
    (config) => {
      console.log('process.env.NODE_ENV',process.env.NODE_ENV);
      if(process.env.NODE_ENV === 'production'){
        //暴露webpack的配置 config ,evn
        const paths = require('react-scripts/config/paths');
        // 配置打包目录输出到dist/ 目录中
        paths.appBuild = path.join(path.dirname(paths.appBuild), 'dist');
        config.output.path = paths.appBuild;
        // 配置访问子目录/
        paths.publicUrlOrPath = './'
        config.output.publicPath = './'
      }

      return config
    }

**Comment by WinmezzZ** [comment]
不用这么麻烦，在根目录 `.env` 文件中加入环境变量 `PUBLIC_URL=你的公共路径` 即可

**Comment by yuyunzhi** [comment]
解决了，打包路径的问题。还要区分一下本地调试，和打包调试的目录路径。

PUBLIC_URL=你的公共路径 可以的

**Comment by WinmezzZ** [comment]
> 解决了，打包路径的问题。还要区分一下本地调试，和打包调试的目录路径。
> 
> PUBLIC_URL=你的公共路径 可以的

建议不要区分环境，以免出现开发与生产路径模式不同造成影响，当然，这个看个人具体需求

**Comment by yuyunzhi** [comment]
不然打包，路径是访问不到的

**Comment by WinmezzZ** [comment]
对项目来说这不是个问题，对使用者来说却是个容易忽略的问题，感谢提醒，稍后我会在 README 中标注

**Comment by yuyunzhi** [comment]
因为，我这边打包后的路径不用build 而是dist 所以还是要在 config-overrides.js里修改
