### ISSUE TITLE
项目写的很棒，我想请教下作者，有考虑加分割菜单吗，就是顶部是一级菜单，左侧 是二级菜单

### ISSUE THREAD

**Issue by weiqinke** [WinmezzZ/react-antd-admin#20]
类似pro 的分隔式

**Comment by WinmezzZ** [comment]
本项目重点不在 ui 上，而是如何从 0 构建一个 `React App`，尽量做到简二再简。如果加上顶部菜单则又会有人问如何去掉，如果兼并弄一个动态切换布局则复杂了项目，违背了初衷。所以可能暂时不会考虑添加顶部菜单。 

你可以依照本项目的布局进行修改，在 `src/pages/layout/index.tsx` 目录下，参照 [ant-design](https://ant.design/components/menu-cn/#components-menu-demo-horizontal) 的菜单相关文档进行布局重构。
