### ISSUE TITLE
路由没有进行守卫

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [WinmezzZ/react-antd-admin#22]
你好，作者， 我发现如果我在没有登录的状态下输入其他路由的地址也是可以直接进入的 貌似没有守卫到哦

**Comment by WinmezzZ** [comment]
仔细看[https://github.com/WinmezzZ/react-antd-admin/blob/master/src/routes/index.tsx#L41](https://github.com/WinmezzZ/react-antd-admin/blob/master/src/routes/index.tsx#L41)，只有具备了  ```auth```  属性的 ```WrapperRouteComponent``` 才拥有权限的功能

在 admin 系统中一般建议全部加上 ```auth``` ，如果嫌麻烦可以直接在在 [https://github.com/WinmezzZ/react-antd-admin/blob/master/src/routes/index.tsx#L25](https://github.com/WinmezzZ/react-antd-admin/blob/master/src/routes/index.tsx#L25) 中直接设置 ```auth``` 属性，意味着除了登录以外的页面全部需要权限

另外，为了用户体验， 建议将 [https://github.com/WinmezzZ/react-antd-admin/blob/master/src/routes/pravateRoute.tsx](https://github.com/WinmezzZ/react-antd-admin/blob/master/src/routes/pravateRoute.tsx) 中直接返回到登录页面而不是`403` 页面

**Comment by PlayGuitar-CoderQ** [comment]
谢谢作者的回复，因为我刚进入react也不久，发现你的这个项目用的技术都挺新的，所以特地pull到本地进行学习，不过我个人感觉到路由方面我有点不是很明白，比如如果手动在地址栏填写错误路由的表现，刚启动的时候，因为未登录状态下所以走进了404，正常逻辑应该是刚启动项目进来，未登录会跳转到登陆页面，并且发现子菜单不会收缩(这个我解决了)，登陆时候的一个form提示报错(这个我解决了)。和刚刚说的手动在地址栏填写错误路由，会造成tagView里的 tag.path 报错 ，大佬你会持续迭代的吧 我还想跟着你学这个项目

**Comment by WinmezzZ** [comment]
首先这个项目是有在更新的，技术栈用的也都是比较新，插件的版本更新时我一般也会保持同步更新，issue 一般会及时反馈 bug 会及时修复。

- 其次针对你说的未登录走进了404而没跳转到登录没，你应该仔细看我的上一条回复的最后一句话。
- 然后子菜单不能收缩的问题，昨天有人提过了并且改过了，你可以看下这个 [issue](https://github.com/WinmezzZ/react-antd-admin/issues/23#issue-838407704)
- 登陆时候的一个form提示报错 和 tagView 问题我需要看一下

另外如果你已经确定了是个问题并解决了可以提一个 [pr](https://github.com/WinmezzZ/react-antd-admin/pulls)，帮助我改进。有其他问题的话随时欢迎提问

**Comment by PlayGuitar-CoderQ** [comment]
好的 谢谢作者 我会持续关注你这个项目的 再次谢谢你 开源
