### ISSUE TITLE
Compile issue - Can't resolve ./App 

### ISSUE THREAD

**Issue by Bravo13** [WinmezzZ/react-antd-admin#37]
I just cloned repo and hit `npm install && npm run` and get this
```
Failed to compile.

./src/index.tsx
Module not found: Can't resolve './App' in '/home/bravo13/projects/molfar-crm-admin/src'
```
my node -v is v14.16.0

**Comment by xieyezi** [comment]
@Bravo13 Maybe you can prodvide log in there?

**Comment by WinmezzZ** [comment]
just run the code of `old` branch

**Comment by Bravo13** [comment]
thanks @WinmezzZ looks like solved

**Comment by WinmezzZ** [comment]
> thanks @WinmezzZ looks like solved

The code of the `master` branch is being refactored recently, so it is unstable now, safe code was placed on the `old` branch already.
