### ISSUE TITLE
Development - Next Version

### ISSUE THREAD

**Issue by Dendekky** [WinmezzZ/react-antd-admin#38]
Hi, nice work being done here. When do you figure the nextjs version of this template would be ready?

**Comment by WinmezzZ** [comment]
> Hi, nice work being done here. When do you figure the nextjs version of this template would be ready?

not ready for nextjs yet.

Because the admin system usually does not need seo, but nextjs is mainly for seo, there will be some contradictions between them. You can copy the core code to the nextjs directory and Do some compatible work.
