### ISSUE TITLE
ReferenceError, Cannot access 'createAsyncAction' before initialization

### ISSUE THREAD

**Issue by mrs01dev** [WinmezzZ/react-antd-admin#44]
Please inspect this error:
ReferenceError: Cannot access 'createAsyncAction' before initialization
Module.createAsyncAction
http://localhost:2000/static/js/main.chunk.js:9475:109
Module.<anonymous>
E:/WinmezzZ/src/stores/user.store.ts:59
  56 | // };
  57 | 
  58 | // typed wrapper async thunk function demo, no extra feature, just for powerful typings
> 59 | export const loginAsync = createAsyncAction<LoginParams, boolean>(payload => {
  60 |   return async (dispatch, getState) => {
  61 |     const { result, status } = await apiLogin(payload);
  62 |     if (status) {
View compiled
Module../src/stores/user.store.ts
http://localhost:2000/static/js/main.chunk.js:10046:30
__webpack_require__
E:/WinmezzZ/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
E:/WinmezzZ/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
▶ 2 stack frames were collapsed.
__webpack_require__
E:/WinmezzZ/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
E:/WinmezzZ/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
▶ 2 stack frames were collapsed.
__webpack_require__
E:/WinmezzZ/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
E:/WinmezzZ/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
▶ 2 stack frames were collapsed.
__webpack_require__
E:/WinmezzZ/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
E:/WinmezzZ/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:2000/static/js/main.chunk.js:10500:18
__webpack_require__
E:/WinmezzZ/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
checkDeferredModules
E:/WinmezzZ/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
E:/WinmezzZ/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:2000/static/js/main.chunk.js:1:85

**Comment by WinmezzZ** [comment]
It seems to be all right, and it can't be repeated.
https://github.com/WinmezzZ/react-antd-admin/blob/6f79b6304ea936c823d6ee6430c580ad4d35ebd1/src/stores/user.store.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L5
Try pulling down the code again?

**Comment by WinmezzZ** [comment]
fixed in https://github.com/WinmezzZ/react-antd-admin/blob/ef828065c471858a2e7fd998ef7e876f8f55ffee/src/stores/user.store.ts#L5
