### ISSUE TITLE
tagview question

### ISSUE THREAD

**Issue by FocusHuang** [WinmezzZ/react-antd-admin#48]
假如当前有一个dashboard的标签页，地址是xxx/dashboard，此时在地址栏上输入/permission/404，tagview会新增一个tag并且跳转过去，这个是怎么实现的

**Comment by WinmezzZ** [comment]
通过监听 `pathname` 的变化，去菜单信息里面获取对应的菜单，然后添加到全局的 tagsList 中去（如果已存在只会跳转，如果不存在就添加）

详情看这里： https://github.com/WinmezzZ/react-antd-admin/blob/7f97f2301a9d7d420fb6811539ba9269bf620ece/src/pages/layout/tagView/index.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48
