### ISSUE TITLE
tagView 无法保留状态

### ISSUE THREAD

**Issue by tearf001** [WinmezzZ/react-antd-admin#54]
切换tab时候, tab页内容会根据新路由地址 进行重新渲染,导致状态丢失.
可用通过 useRef 记住 容器中组件,从而进行 保留状态?

```tsx
type TabHolder = {
  key: string;
  name: string;
  page: ReactNode;
  uri: string;
  params: Params;
};
const tabList = useRef(new Map<string, TabHolder>());
```
详细代码见:
[tagView/PersistedTabs.tsx#L41](https://github.com/tearf001/react-antd-admin/blob/master/src/pages/layout/tagView/PersistedTabs.tsx#L41)

**Comment by WinmezzZ** [comment]
感谢反馈。

这个 tagView 稚嫩算是一种菜单的快捷方式，原始的切换路由也是无法保存状态的，这点不是初衷。

当然保存状态的情况下，用户体验会更佳。但是通常不建议这么做，太多的 `React State` 和 `React DOM` 保存在内存中的话，性能方面值得权衡，需要通过大量的测试以及带来的一系列未知的后果。

如果你能打消这些疑虑，欢迎提供 PR。

**Comment by WinmezzZ** [comment]
因为太久远并且不活跃，关闭此issue

**Comment by niyg** [comment]
作者全部菜单打开的情况已经很卡了，特别是最后一个打开的时候，有什么优化方式不，我也遇到类似的问题了。几十个菜单，很难受
