### ISSUE TITLE
Blank page https://react-admin.winme.dev/

### ISSUE THREAD

**Issue by marquicus** [WinmezzZ/react-antd-admin#77]
When openning chrome or firefox it throws blank page :(

**Comment by zaxtseng** [comment]
项目启动在本地，显示如下：
`rootReducer.tsx:9 Uncaught ReferenceError: Cannot access 'userReducer' before initialization`。
另外文档也无法显示。

**Comment by WinmezzZ** [comment]
稍等，正在处理
