### ISSUE TITLE
询问下项目在vsocde中保存css文件会属性排序用的什么插件

### ISSUE THREAD

**Issue by GeSnowBoy** [WinmezzZ/react-antd-admin#83]
例如我这样写代码：
<img width="253" alt="image" src="https://github.com/WinmezzZ/react-antd-admin/assets/17561864/9fb94479-f665-4940-b1f5-70ff919d137c">
格式化以后就属性就自动排序了：
<img width="222" alt="image" src="https://github.com/WinmezzZ/react-antd-admin/assets/17561864/2541edd6-0731-4158-ba07-02a414cfa27b">

**Comment by jingjing20** [comment]
> 例如我这样写代码： <img alt="image" width="253" src="https://user-images.githubusercontent.com/17561864/250487017-9fb94479-f665-4940-b1f5-70ff919d137c.png"> 格式化以后就属性就自动排序了： <img alt="image" width="222" src="https://user-images.githubusercontent.com/17561864/250487125-2541edd6-0731-4158-ba07-02a414cfa27b.png">

<img width="446" alt="image" src="https://github.com/WinmezzZ/react-antd-admin/assets/56109788/309240f8-d11f-4bfe-8915-fb0490f776d2">
