### ISSUE TITLE
关闭当前tab后页面不会跳到其他

### ISSUE THREAD

**Issue by hefeiping0808** [WinmezzZ/react-antd-admin#85]
关闭前：
![1](https://github.com/WinmezzZ/react-antd-admin/assets/64398073/20939820-3a4a-4a8d-ac5e-9cbf55dc9f41)

关闭后：
![2](https://github.com/WinmezzZ/react-antd-admin/assets/64398073/3971bea8-9f08-4a06-b0e3-5e59ca8abd2e)

页面还是原来的表格页面

**Comment by WinmezzZ** [comment]
感谢反馈，已修复~
